### ISSUE TITLE
enableAccessibilityVoice not working in config

### ISSUE THREAD

**Issue by w4dd325** [sclavijosuero/wick-a11y#10]
When setting _enableAccessibilityVoice_ to true in the config, when I run a test I get no options for voice. 

But when I pass _enableAccessibilityVoice_  as a command line arg ```npx cypress open -- env enableAccessibilityVoice=true``` it does give me the option for voice. 

Video attached.
https://github.com/user-attachments/assets/4569ed75-c0d7-4c38-80fe-9d7fdb07d264

**Comment by sebastianclavijo** [comment]
@w4dd325 , to set cypress environment variables in the `cypress.config.js` file you need to do as a sub property within the **env** property, instead of within **e2e**.

This is an example:
```
module.exports = defineConfig({
      // [...]
      env: {
            enableAccessibilityVoice: true
      }
      // [...]
});
```

You can also set it directly in the file `cypress.env.json`.
Details are explained in the [Configuration](https://github.com/sclavijosuero/wick-a11y?tab=readme-ov-file#configuration) section of the doc.

Cheers

**Comment by w4dd325** [comment]
All working - user error!! thank you!
